language: node_js
node_js:
  - "lts/*"

before_script:
  - npm install -g gatsby-cli
  - npm install -g typescript

deploy:
  provider: script
  script: yarn deploy
  skip_cleanup: true
  on:
    branch: master
